version: '3.8'

services:
  mongodb:
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password}
    volumes:
      - mongodb_data_prod:/data/db
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  auth-service:
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=production
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  api-gateway:
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - AUTH_SERVICE_URL=auth-service:50051
      - NODE_ENV=production
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

volumes:
  mongodb_data_prod:
    driver: local
