// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.3
//   protoc               v3.20.3
// source: proto/common.proto

/* eslint-disable */

export enum UserRole {
  USER_ROLE_UNSPECIFIED = 0,
  USER_ROLE_USER = 1,
  USER_ROLE_ADMIN = 2,
  USER_ROLE_SUPER_ADMIN = 3,
  UNRECOGNIZED = -1,
}

export enum SortOrder {
  SORT_ORDER_UNSPECIFIED = 0,
  SORT_ORDER_ASC = 1,
  SORT_ORDER_DESC = 2,
  UNRECOGNIZED = -1,
}

export interface User {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
  phone?: string | undefined;
  bio?: string | undefined;
  avatarUrl?:
    | string
    | undefined;
  /** Unix timestamp */
  createdAt: number;
  /** Unix timestamp */
  updatedAt: number;
  /** Unix timestamp */
  lastLoginAt: number;
  isVerified: boolean;
  isActive: boolean;
  role: UserRole;
  preferences: UserPreferences | undefined;
}

export interface UserPreferences {
  emailNotifications: boolean;
  pushNotifications: boolean;
  marketingEmails: boolean;
  language: string;
  timezone: string;
  /** light, dark, auto */
  theme: string;
}

export interface PaginationInfo {
  currentPage: number;
  totalPages: number;
  totalItems: number;
  itemsPerPage: number;
  hasNext: boolean;
  hasPrevious: boolean;
}
